### PR TITLE
Feature/contact feedback mail

### PR DESCRIPTION
**Pull request by EnriColombo**

### CODE REVIEW

**Comment by EnriColombo** [comment]
Ops! Something went wrong! Mumble....

**Comment by davide-casiraghi** [comment]
My fault ...
I did s mistake in the migration I added..

**Comment by davide-casiraghi** [comment]
But from a quick check I don't see the problem yet..

**Comment by davide-casiraghi** [comment]
Probably we have to add the email to the testimonial factory and tests

**Comment by davide-casiraghi** [comment]
I fixed it  adding nullable to the email field that I have added with the last migration

**Pull request merged**
