### PR TITLE
Feature/sitemap

### PR DESCRIPTION
**Pull request by EnriColombo**
tests/Unit/Commands/GenerateSitemapTest.php

The test is incomplete. I need suggestions ;)
I was thinking of testing if there is a post url with slug 'test' on sitemap.xml file...
The same about event, tag and glossary.

Let me know...:)

### CODE REVIEW

**Comment by davide-casiraghi** [comment]
I think that you can load the content of the sitemap file and as you say, check if the slug exists in it.

Maybe you can do a more complicated slug then 'test' 
g. with a content that has spaces in the title.
So you generate the slug with dash and without capital letters.

And then yes, you check if it exist in the sitemap that you load with an assertion like
`$this->assertStringContainsString('flour', $plaintext);`

**Comment by EnriColombo** [comment]
Review the GenerateSitemapTest.php and let me know ;)

**Comment by davide-casiraghi** [comment]
Hi Enry, 
there are some problems with the tests.
When you fix I will merge.

Good job!

**Comment by EnriColombo** [comment]
I noticed 2 tests failed in PostControllerTest.php (lines 61 and 85) when I added dev packages laravel-debugbar and laravel-query-detector (I suppose the problem is from the last one).
I'm going to remove them and make further investigation ;)

**Comment by EnriColombo** [comment]
TravisCI on my branch  repo says:
[Build #71 was fixed](https://travis-ci.org/github/EnriColombo/movement_meets_life_nova/builds/762581893?utm_medium=notification&utm_source=email)
I can't understand....

**Comment by davide-casiraghi** [comment]
Ok, I will merge and then you can pull the master and see if something fails..

**Pull request merged**
